apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/minikube  # Path in your GitHub repository where the manifests are located
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
  targetNamespace: default
